version: '3.8'

services:
  frontend:
    container_name: kbb-frontend
    image: kbb-frontend:${Frontend_TAG}
    build:
      context: ${DockerFileDir}
      dockerfile: Dockerfile.frontend
    ports:
      - 5000:5000

  backend:
    container_name: kbb-backend
    image: kbb-backend:${Backend_TAG}
    build:
      context: ${DockerFileDir}
      dockerfile: Dockerfile.backend
    ports:
      - 5001:5000

  mysqldb:
    container_name: kbb-db
    build:
      context: ${DockerFileDir}
      dockerfile: Dockerfile.db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root

  adminer:
    container_name: kbb-adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
      ADMINER_DESIGN: pappu687
    ports:
      - 8080:8080
