version: '3.8'

services:
  frontend:
    container_name: kbb-frontend
    image: kbb-frontend:${Frontend_TAG}
    depends_on:
      - backend
    # todo: add port mapping

  backend:
    container_name: kbb-backend
    image: kbb-backend:${Backend_TAG}
    build:
      context: ${DockerFileDir}
      dockerfile: Dockerfile.backend
    depends_on:
      - mysqldb
    ports:
      - 5000:5000

  mysqldb:
    container_name: kbb-db
    image: kbb-db:${Backend_TAG}
    volumes:
      - "./sql-scripts:/docker-entrypoint-initdb.d"
    build:
      context: ${DockerFileDir}
      dockerfile: Dockerfile.db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root

  adminer:
    container_name: kbb-adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
      ADMINER_DESIGN: pappu687
    ports:
      - 8080:8080

  initmysqldb:
    image: kbb-db-init:${Backend_TAG}
    container_name: kbb-db-init
    build:
      context: ${DockerFileDir}
      dockerfile: Dockerfile.db_init
    depends_on:
      - mysqldb
